### ISSUE TITLE
Remove Eq constraint on props

### ISSUE THREAD

**Issue by tysonzero** [liqula/react-hs#49] opened 2017-08-02 03:24 UTC
So I want to pass functions into child views, which I was able to do in react.js without any difficulty, but I cannot do this unless the `Eq` constraint on props is removed.

Particularly I want to pass in lenses of sorts, functions of the form `(LocalState -> IO LocalState) -> GlobalState -> IO GlobalState`, coupling that with `data Action = Action (GlobalState -> IO GlobalState)`, I am able to have local modifiable state that isn't going to get destroyed by a rerender.

This actually pretty much solves the problems I was complaining about earlier, as I know longer need true local state (not even mkStatefulView), with all its complexities and volatilities. And all this without sacrificing the ability to have multiple stateful instances of the same view. 

I was curious what the purpose of Eq on props was, I'm assuming it is an optimization to try and avoid unnecessary rerendering. One thing to note though is that if you have a very large state that is only partially displayed, such as with paging, calling `==` might actually be a pessimization, particularly if it turns out that the state is different anyway and so calling `==` was a total waste.

I propose instead using either `reallyUnsafePtrEquality#` or `unsafePerformIO` combined with stable names. This sounds dangerous but is actually pretty commonly done and as long as it is just used to avoid rerendering it is not observable. It allows functions as props just fine and also avoids the pessimization risk.

**Comment by fisx** [comment] 2017-08-02 05:15
duplicate of #8

**Closed as completed by fisx** 2017-08-02 05:15 UTC

**Comment by fisx** [comment] 2017-08-02 05:27
(I tried to respond to your questions in #8.)
